name: "Einkaufsliste"
version: "1.0.6"
slug: "einkaufsliste"
description: "Einfache Einkaufsliste mit Anzahl, Kategorie und Produkt"
url: "https://github.com/wolli112-vc/einkaufsliste"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
init: false
ingress: true
ingress_port: 8099
panel_icon: "mdi:cart"
panel_title: "Einkaufsliste"
panel_admin: false
options:
  log_level: info
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
map:
  - share:rw
